# Generated by Django 5.2.1 on 2025-06-09 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_maincategory_created_at'),
    ]

    operations = [
    ]
