# Generated by Django 5.2.1 on 2025-06-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_useractivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'User Activities'},
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='activity',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Register'), ('ADD_TO_CART', 'Add to Cart'), ('PAGE_VIEW', 'Page View')], default='PAGE_VIEW', max_length=20),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='additional_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
